BEGIN TRANSACTION;
--DROP TABLE IF EXISTS config;
CREATE TABLE IF NOT EXISTS config (
	server TEXT NOT NULL,
	key TEXT NOT NULL,
	value TEXT,
	UNIQUE(server, key)
);
--DROP TABLE IF EXISTS birthdays;
CREATE TABLE IF NOT EXISTS birthdays (
	server TEXT NOT NULL,
	user TEXT NOT NULL,
	year INTEGER,
	month INTEGER NOT NULL,
	day	INTEGER NOT NULL,
	UNIQUE(server, user)
);
COMMIT;
